// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB7bDxl9NVbv8hOU5x7l7C1F-KgnjkYsRA',
    appId: '1:431648024865:web:017fc4c2e6521efb763660',
    messagingSenderId: '431648024865',
    projectId: 'ibip-test',
    authDomain: 'ibip-test.firebaseapp.com',
    storageBucket: 'ibip-test.firebasestorage.app',
    measurementId: 'G-T7Y2X18MPJ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBoU_hiaH7iOM4q4LDQy2cQ84Kdha6iwek',
    appId: '1:431648024865:android:691829667315372d763660',
    messagingSenderId: '431648024865',
    projectId: 'ibip-test',
    storageBucket: 'ibip-test.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyApI43mZLDld6C1_EMiADDWxjm2o0VA03E',
    appId: '1:431648024865:ios:7fbd3c2fed6386d6763660',
    messagingSenderId: '431648024865',
    projectId: 'ibip-test',
    storageBucket: 'ibip-test.firebasestorage.app',
    iosBundleId: 'com.example.surgiassistIbipLnct',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyApI43mZLDld6C1_EMiADDWxjm2o0VA03E',
    appId: '1:431648024865:ios:7fbd3c2fed6386d6763660',
    messagingSenderId: '431648024865',
    projectId: 'ibip-test',
    storageBucket: 'ibip-test.firebasestorage.app',
    iosBundleId: 'com.example.surgiassistIbipLnct',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyB7bDxl9NVbv8hOU5x7l7C1F-KgnjkYsRA',
    appId: '1:431648024865:web:c0299d785246e574763660',
    messagingSenderId: '431648024865',
    projectId: 'ibip-test',
    authDomain: 'ibip-test.firebaseapp.com',
    storageBucket: 'ibip-test.firebasestorage.app',
    measurementId: 'G-7HXCX5GS38',
  );
}
